### ISSUE TITLE
Integration not working after upgrading HA to 2023.7 version

### ISSUE THREAD

**Issue by dariuszuzar** [elupus/hass_nibe#184]
Logger: homeassistant.setup
Source: custom_components/nibe/__init__.py:18 
Integration: Nibe Uplink Heat Pumps (documentation) 
First occurred: 19:42:04 (1 occurrences) 
Last logged: 19:42:04

Setup failed for custom integration nibe: Unable to import component: cannot import name 'Uplink' from 'nibeuplink' (/usr/local/lib/python3.11/site-packages/nibeuplink/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/nibe/__init__.py", line 18, in <module>
    from nibeuplink import Uplink, UplinkSession
ImportError: cannot import name 'Uplink' from 'nibeuplink' (/usr/local/lib/python3.11/site-packages/nibeuplink/__init__.py)

**Comment by elupus** [comment]
Did you upgrade nibe component?

**Comment by dariuszuzar** [comment]
The component was in the newest version. Upgrading Home Assistant to version 2023.7.3 solved the problem.
