### ISSUE TITLE
Integration stopped working in HA 2023.5.X

### ISSUE THREAD

**Issue by nljungstrand** [elupus/hass_nibe#181]
Integration stopped working when updating HA core above 2023.4.6.

Tried reinstalling integration, tried making a new app in NibeAPI, still not working. 

When installing integration I get this message:

Error setting up entry for nibe
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nibe/__init__.py", line 233, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, FORWARD_PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
